package co.fcv.citas.identity;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status; import java.security.SecureRandom; import java.util.Base64; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest @AutoConfigureMockMvc class AuthControllerTest {
 @Autowired MockMvc mvc; static String secret(){byte[] b=new byte[48];new SecureRandom().nextBytes(b);return Base64.getEncoder().encodeToString(b);}
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("TEST_JWT_ACCESS_SECRET",AuthControllerTest::secret);r.add("TEST_JWT_REFRESH_SECRET",AuthControllerTest::secret);}
 String register(String email,String doc){return "{\"firstNames\":\"Ana\",\"lastNames\":\"Prueba\",\"documentType\":\"CC\",\"documentNumber\":\""+doc+"\",\"email\":\""+email+"\",\"phone\":\"3000000000\",\"password\":\"SecurePass123\"}";}
 @Test void registersAndPreventsDuplicates() throws Exception {mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register("ana@example.test","1"))).andExpect(status().isCreated());mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register("ana@example.test","2"))).andExpect(status().isConflict());mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register("other@example.test","1"))).andExpect(status().isConflict());}
 @Test void loginAndRefreshWorkAndBadPasswordFails() throws Exception {mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register("login@example.test","3"))).andExpect(status().isCreated());String body=mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"login@example.test\",\"password\":\"SecurePass123\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(body).contains("accessToken","refreshToken");String refresh=body.replaceAll(".*\\\"refreshToken\\\":\\\"([^\\\"]+)\\\".*","$1");mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isOk());mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isUnauthorized());mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"login@example.test\",\"password\":\"wrong\"}")).andExpect(status().isUnauthorized());}
}
