package co.fcv.citas.identity;
import io.jsonwebtoken.Jwts; import io.jsonwebtoken.security.Keys; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class AuthService {
 private static final Duration ACCESS=Duration.ofMinutes(15), REFRESH=Duration.ofDays(7); private final UserRepository users; private final RefreshTokenRepository refreshes; private final PasswordEncoder encoder; private final String accessSecret,refreshSecret; private final SecureRandom random=new SecureRandom();
 AuthService(UserRepository users,RefreshTokenRepository refreshes,PasswordEncoder encoder,@Value("${app.jwt.access-secret}") String accessSecret,@Value("${app.jwt.refresh-secret}") String refreshSecret){this.users=users;this.refreshes=refreshes;this.encoder=encoder;this.accessSecret=accessSecret;this.refreshSecret=refreshSecret;}
 @Transactional AuthController.RegisteredUser register(AuthController.RegisterRequest r){String email=r.email().trim().toLowerCase(Locale.ROOT); if(users.existsByEmailIgnoreCase(email)||users.existsByDocumentTypeAndDocumentNumber(r.documentType(),r.documentNumber())) throw new ConflictException("EMAIL_OR_DOCUMENT_ALREADY_EXISTS"); try {UserEntity u=users.save(new UserEntity(r.firstNames().trim(),r.lastNames().trim(),r.documentType().trim(),r.documentNumber().trim(),email,r.phone().trim(),encoder.encode(r.password()))); return new AuthController.RegisteredUser(u.id,u.email,u.role);}catch(DataIntegrityViolationException e){throw new ConflictException("EMAIL_OR_DOCUMENT_ALREADY_EXISTS");}}
 @Transactional AuthController.SessionResponse login(AuthController.LoginRequest r){UserEntity u=users.findByEmailIgnoreCase(r.email().trim()).filter(x->encoder.matches(r.password(),x.passwordHash)).orElseThrow(()->new UnauthorizedException("INVALID_CREDENTIALS"));return issue(u);}
 @Transactional AuthController.SessionResponse refresh(String raw){RefreshTokenEntity t=refreshes.findByTokenHash(hash(raw)).filter(x->x.expiresAt.isAfter(Instant.now())).orElseThrow(()->new UnauthorizedException("INVALID_REFRESH_TOKEN")); UserEntity user=t.user; refreshes.delete(t);return issue(user);}
 private AuthController.SessionResponse issue(UserEntity u){Instant now=Instant.now();String access=Jwts.builder().subject(u.id.toString()).claim("role",u.role).issuedAt(Date.from(now)).expiration(Date.from(now.plus(ACCESS))).signWith(Keys.hmacShaKeyFor(accessSecret.getBytes(StandardCharsets.UTF_8))).compact(); byte[] bytes=new byte[48];random.nextBytes(bytes);String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);refreshes.save(new RefreshTokenEntity(u,hash(raw),now.plus(REFRESH)));return new AuthController.SessionResponse(access,raw,"Bearer",ACCESS.toSeconds());}
 private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest((refreshSecret+":"+value).getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
